Improved doxigen for Yarp devices
robotology/yarp pull request #2348
Opened 2020-08-31 12:19 UTC by randaz81

Improved doxigen documentation for Yarp devices

#2346 needs to be merged first, then rebase

2020-08-31 12:30 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +        depth_ok = m_depth_input_processor->getLastDepthData(depthFrame, *depthStamp);
Codacy found an issue: [Variable 'depth_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 12:30 UTC, drdanz commented on src/devices/RGBDRosConversionUtils/rosPixelCode.cpp
> +int Ros2YarpPixelCode(std::string roscode)
Codacy found an issue: [Function parameter 'roscode' should be passed by const reference.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 12:30 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +    bool rgb_ok = false;
Codacy found an issue: [The scope of the variable 'rgb_ok' can be reduced.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 12:30 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +        bool depth_ok = m_depth_input_processor->getLastDepthData(depthImage, *timeStamp);
Codacy found an issue: [Variable 'depth_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 12:30 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +    bool depth_ok = false;
Codacy found an issue: [The scope of the variable 'depth_ok' can be reduced.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 12:30 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +    bool depth_ok = false;
Codacy found an issue: [Variable 'depth_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 12:30 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +        bool rgb_ok = m_rgb_input_processor->getLastRGBData(rgbImage, *timeStamp);
Codacy found an issue: [Variable 'rgb_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 12:30 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +    bool rgb_ok = false;
Codacy found an issue: [Variable 'rgb_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 12:30 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +        rgb_ok = m_rgb_input_processor->getLastRGBData(colorFrame, *colorStamp);
Codacy found an issue: [Variable 'rgb_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 13:39 UTC, drdanz requested changes
I think you should rebase this and remove the commits that do not belong to this PR.
Beside that, documentation is always welcome

2020-08-31 14:31 UTC, randaz81 commented
> I think you should rebase this and remove the commits that do not belong to this PR.
> Beside that, documentation is always welcome

@drdanz As mentioned in the description, to avoid conflicts, _#2346 needs to be merged first, then rebase_, because this PR changes the documentation of that device too.

2020-08-31 15:14 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +    bool rgb_ok = false;
Codacy found an issue: [The scope of the variable 'rgb_ok' can be reduced.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 15:14 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +        bool depth_ok = m_depth_input_processor->getLastDepthData(depthImage, *timeStamp);
Codacy found an issue: [Variable 'depth_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 15:14 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +    bool depth_ok = false;
Codacy found an issue: [The scope of the variable 'depth_ok' can be reduced.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 15:14 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +    bool rgb_ok = false;
Codacy found an issue: [Variable 'rgb_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 15:14 UTC, drdanz commented on src/devices/RGBDRosConversionUtils/rosPixelCode.cpp
> +int Ros2YarpPixelCode(std::string roscode)
Codacy found an issue: [Function parameter 'roscode' should be passed by const reference.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 15:14 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +    bool depth_ok = false;
Codacy found an issue: [Variable 'depth_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 15:14 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +        rgb_ok = m_rgb_input_processor->getLastRGBData(colorFrame, *colorStamp);
Codacy found an issue: [Variable 'rgb_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 15:14 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +        bool rgb_ok = m_rgb_input_processor->getLastRGBData(rgbImage, *timeStamp);
Codacy found an issue: [Variable 'rgb_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-08-31 15:14 UTC, drdanz commented on src/devices/RGBDSensorFromRosTopic/RGBDSensorFromRosTopic.cpp
> +        depth_ok = m_depth_input_processor->getLastDepthData(depthFrame, *depthStamp);
Codacy found an issue: [Variable 'depth_ok' is assigned a value that is never used.](https://app.codacy.com/manual/robotology/yarp/pullRequest?prid=6096993)

2020-09-09 11:01 UTC, drdanz commented
@randaz81 I think that if you rebase this, we can merge it

2020-09-22 15:08 UTC, drdanz commented
/rebase

2020-09-22 15:11 UTC, merged

2020-09-22 15:11 UTC, drdanz commented
Merged, thanks.