Fix/add envelope mas server
robotology/yarp pull request #2361
Opened 2020-09-14 10:37 UTC by Nicogene

This PR adds the envelope to the messages streamed by the `measures:o` port of `multipleanalogsensorsserver`.

Please review code.

2020-09-14 10:46 UTC, pattacini approved these changes
Fine with this thanks @Nicogene 

@traversaro, is the choice `Time::now()` for the stamp the best or do we have other timestamps around that we can use in this context as well?

2020-09-14 10:49 UTC, traversaro commented
> @traversaro, is the choice `Time::now()` for the stamp the best or do we have other timestamps around that we can use in this context as well?

I don't think we can do a lot with the timestamp that are available for each sensor, as they could refer to different machine with different time settings. The only reasonable thing to do seems the one proposed in the PR.

2020-09-14 10:52 UTC, traversaro requested changes
Two small comments: 
* Does it make sense to reset `m_msgCount` when the port is opened? 
* Can you add a line on this in the `multipleanalogsensorsserver`  docs? 

For @drdanz: this is changing the ABI of the MultipleAnalogSensorsServer class, that however is not installed as an header, is this ok?

2020-09-14 12:02 UTC, Nicogene commented
> Does it make sense to reset m_msgCount when the port is opened?

Mm it makes sense if it is possible to make it run, make attach, then detach and once again attach.
Is it possible?

> Can you add a line on this in the multipleanalogsensorsserver docs?

Where can I add it?

2020-09-14 12:04 UTC, traversaro commented
> > Does it make sense to reset m_msgCount when the port is opened?
> 
> Mm it makes sense if it is possible to make it run, make attach, then detach and once again attach.
> Is it possible?

As a PolyDriver can be run from arbitrary C++ code, in theory it is possible.

> Where can I add it?

https://github.com/robotology/yarp/pull/2361/files#diff-592976e08f1ed16341e14981e89745ffL27

2020-09-14 12:35 UTC, drdanz commented
Since you are updating it with `Time::now()`, and you are keeping an external counter, I believe it would make more sense to keep a `Stamp` as class member, and call [`update()`](http://www.yarp.it/classyarp_1_1os_1_1Stamp.html#a2589971bf4eed0eb8d6c8f89b143efbc)... This would, at least, avoid calling the `Stamp` ctor and dtor every time the data is sent...

2020-09-14 12:51 UTC, traversaro commented on src/devices/multipleanalogsensorsserver/MultipleAnalogSensorsServer.h
> + * The data on the /${name}/measures:o is streamed every ${period} milliseconds, and an envelope to each data is added with a timestamp of the yarp::os::Time::now()
```suggestion
 * The data on the /${name}/measures:o is streamed every ${period} milliseconds, and an envelope to each data is added with a timestamp obtained by calling the yarp::os::Time::now() method
```

2020-09-14 12:51 UTC, traversaro approved these changes
Just a small remaining suggestion.

2020-09-15 11:54 UTC, Nicogene commented
/rebase

2020-09-15 15:33 UTC, drdanz approved these changes
LGTM, but please fix the space, since it will probably break the changelog page

2020-09-15 15:33 UTC, drdanz commented on doc/release/yarp_3_4/fix_addEnvelopeMASServer.md
> +fix_addEnvelopeMASServer{#yarp_3_4}
Please add a space before `{`

2020-09-15 15:46 UTC, merged