Map2DLocation::is_near_to
robotology/yarp pull request #2407
Opened 2020-11-13 09:03 UTC by randaz81

Added method Map2DLocation::is_near_to()

2020-11-17 15:52 UTC, drdanz requested changes
LGTM, just fix the changelog...

2020-11-17 15:52 UTC, drdanz commented on doc/release/master/location_is_near_to.md
> +* Added method Map2DLocation::is_similar_to()
```suggestion
* Added method Map2DLocation::is_near_to()
```

2020-11-20 11:17 UTC, drdanz commented
/rebase

2020-11-20 12:45 UTC, drdanz commented
/rebase

2020-11-20 12:47 UTC, drdanz commented
/squash

2020-11-20 14:21 UTC, drdanz commented
@randaz81 `dev::Navigation2DClientTest` test is failing

2020-11-21 11:30 UTC, randaz81 commented
@drdanz issue fixed, PR rebased and merged

2020-11-21 11:31 UTC, merged