Added a README for devices
robotology/yarp pull request #2646
Opened 2021-07-08 08:39 UTC by elandini84

Added a README markdown file to `src/devices` folder that shows the current  development status of all the devices in the folder.

2021-07-08 08:47 UTC, traversaro commented
Is this linked in some way from the main README or in the doxygen documentation? In my experience README in nested directories are quite hard to find, unless they are linked directly or indirectly in the main documentation entry points.

2021-07-08 10:06 UTC, elandini84 commented
> Is this linked in some way from the main README or in the doxygen documentation? In my experience README in nested directories are quite hard to find, unless they are linked directly or indirectly in the main documentation entry points.

This is a really god point. This file is aimed directly to developers and not to a generic YARP user. Therefore I do not know if it should be in the main README or in the doxygen documentation. Every suggestion is welcome 😊

2021-07-08 11:14 UTC, traversaro commented
Ah sorry, I misunderstood its role then.

2021-07-09 14:05 UTC, drdanz commented
Link to the rendered README: https://github.com/elandini84/yarp/tree/dox_deviceReadme/src/devices

2021-07-09 14:08 UTC, drdanz requested changes
Can you please fix this and rebase over latest master?

2021-07-09 14:08 UTC, drdanz commented on src/devices/README.md
> +## Yarp devices
```suggestion
## YARP devices
```

2021-07-09 15:02 UTC, merged