Add implementation for friction parameters
robotology/yarp pull request #2805
Opened 2022-02-17 22:37 UTC by sgiraz

What's new in this PR:
- In [ITorqueControl.h][1] have been added 4 new friction parameters: `viscousUp`, `viscousUp`, `coulombUp`, `coulombDown`.
- the definitions of all the `get/set` functions have been updated accordingly.
- A new ControlTorqueTest source has been added to the test folder in order to validate the implementation of the new parameters

**Notes:**
- The implementation has been tested successfully with the new test provided with this PR.

### True positive detection ✅

![image](https://user-images.githubusercontent.com/18039045/154572956-d92016fc-7e6a-4d2f-ac9d-0989f4c7d07a.png)

### False positive detection ✅

![image](https://user-images.githubusercontent.com/18039045/154574580-bf9c63d4-dbb7-4e4b-bb6a-8af84d473f48.png)

[1]: (https://github.com/robotology/yarp/compare/master...sgiraz:master#diff-a6d521af362a51d273c0ced3cd303cf4d7eaf66795f7514c6b33f471ea962254)

2022-02-18 13:13 UTC, randaz81 requested changes
- [ ] measurement units conversion layer (missing in `ImplementTorqueControl.cpp`) to be implemented and tested
- [ ] changelog (missing)

2022-02-21 10:38 UTC, sgiraz commented
> * [ ]  measurement units conversion layer (missing in `ImplementTorqueControl.cpp`) to be implemented and tested
> * [ ]  changelog (missing)

Done

2022-03-02 22:14 UTC, pattacini commented
Hi @randaz81 

Can we merge the PR? It's kind of blocking all the other PR's we have in the pipeline.

2022-03-07 14:56 UTC, randaz81 commented
Merged even if there are some errors in the CI, that should be hopefully fixed by https://github.com/robotology/yarp/pull/2811

2022-03-07 14:58 UTC, merged