FrameGrabber_nwc_yarp: fix bug that forces images to be sent through RPC calls
robotology/yarp pull request #2990
Opened 2023-07-10 11:40 UTC by davidegorbani

Together with @traversaro and @HosameldinMohamed, we found out that the `frameGrabber_nwc_yarp` is using an RPC port to get the image of a camera because `m_streamerReceiver` is not defined; we added the function `setStreamReceiver` and in this way, the object `m_streamerReceiver` is defined and we avoid continuously calling the function [getImage](https://github.com/robotology/yarp/blob/99f5a8a2c728b50300d02bada44fe8fc85df5636/src/devices/frameGrabber_nwc_yarp/FrameGrabber_nwc_yarp.cpp#L145C115-L145C115) which uses an RPC port to receive the image and it slows the process.

2023-07-10 11:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/robotology/yarp?pullRequest=2990) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/robotology/yarp?pullRequest=2990) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/robotology/yarp?pullRequest=2990) it.</sub>

2023-07-10 12:21 UTC, randaz81 commented on src/devices/frameGrabber_nwc_yarp/FrameGrabber_nwc_yarp.cpp
> +    FrameGrabberOf_ForwarderWithStream<yarp::sig::ImageOf<yarp::sig::PixelRgb>>::setStreamReceiver(&streamReceiver);
This block of code could be better placed at line ~202-203 after the streamReceiver.open()

2023-07-10 12:22 UTC, randaz81 requested changes
see the comment below.

2023-07-10 12:51 UTC, davidegorbani commented
Thank you @randaz81 for your comment, I modified the code and added a changelog.

2023-07-12 13:54 UTC, randaz81 approved these changes

2023-07-12 13:57 UTC, merged